//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ConexionDB
{
    using System;
    using System.Collections.Generic;

    
    public partial class LIBRO
    {
        public long ID_LIBRO { get; set; }
        public string NOMBRE_LIBRO { get; set; }
        public string DESCRIPCION { get; set; }
        public string AUTOR { get; set; }
        public string EDITORIAL { get; set; }
        public long PRECIO_UNITARIO { get; set; }
        public long CANTIDAD_DISPONIBLE { get; set; }
        public string PORTADA { get; set; }
        public Nullable<System.DateTime> FECHA_PUBLICACION { get; set; }
        public string CATEGORIA { get; set; }
    }
}
